module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  rootDir: '.',
  collectCoverageFrom: ['**/*.(t|j)s'],
  coveragePathIgnorePatterns: [
    'node_modules',
    'test-config',
    'interfaces',
    'main.ts',
    '.module.ts',
    '.e2e-spec.ts',
    '.mock.ts',
  ],
  coverageDirectory: './coverage',
  roots: ['<rootDir>/apps/', '<rootDir>/libs/'],
  moduleFileExtensions: ['js', 'json', 'ts'],
  transformIgnorePatterns: ['^.+\\.js$'],
  setupFiles: ['<rootDir>/libs/utils/src/test/testSetUp.ts'],
  clearMocks: true,
  verbose: true,
  // moduleNameMapper: {
  //   '^@libs/src(|/.*)$': '<rootDir>/libs/src/$1',
  //   '^@app/test(|/.*)$': '<rootDir>/libs/test/src/$1',
  //   '^@api/test(|/.*)$': '<rootDir>/apps/api/test/$1',
  //   '^@admin/src(|/.*)$': '<rootDir>/apps/admin/src/$1',
  //   '^@admin/test(|/.*)$': '<rootDir>/apps/admin/test/$1',
  //   '^@api/src(|/.*)$': '<rootDir>/apps/api/src/$1',
  // },
};
