name: Docs checker

on:
  pull_request:
    branches:
      - develop

jobs:
  Check-docs-changed:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" above.

    runs-on: ubuntu-latest # windows-latest || macos-latest
    permissions:
      pull-requests: read
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run a step if README.md was modified
        if: ${{ !contains(steps.changed-files.outputs.modified_files, 'README.md') }}
        run: echo Docs Not changed && exit 1
